import fs from 'node:fs';

/**
 * @returns The generated code as string
 *
 * @throws Error
 **/
const writeSourceFile = (filename: string, input: string) => {
  fs.writeFileSync(
    filename,
    `/**
 * This file is autogenerated. Changes will be lost.
 */
 
 ${input}`,
  );

  console.log('Generated', filename);
};

export default writeSourceFile;
