name: Build new tag

on:
  push:
    branches: [ main, ci_docker-building ]
    #tags:
    #  - 'v*'

jobs:
  build:
    #needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag thechristophe/openapi-typebox:${{ github.ref_name }} --target prod

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the latest Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/thechristophe/openapi-typebox:latest

      - name: Push the Docker image with the release tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/thechristophe/openapi-typebox:${{ github.ref_name}}
